### ISSUE TITLE
Z compression in FileCompress task is not working

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-compress#60]
### Expected Behavior

The given flow example with Z compress should work, and successfully compress the file using Z compression.
```
id: "file_compress"
type: "io.kestra.plugin.compress.FileCompress"
from: "{{ inputs.files }}"
compression: Z
```

### Actual Behaviour

The given flow example on this [page](https://kestra.io/plugins/plugin-compress/tasks/io.kestra.plugin.compress.FileCompress) errors out with the following error:

```
2024-02-17 16:48:47.942Unknown compression 'Z'
2024-02-17 16:48:47.942java.lang.IllegalArgumentException: Unknown compression 'Z'
	at io.kestra.plugin.compress.AbstractTask.compressorOutputStream(AbstractTask.java:106)
	at io.kestra.plugin.compress.FileCompress.run(FileCompress.java:51)
	at io.kestra.plugin.compress.FileCompress.run(FileCompress.java:20)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:729)
```

### Steps To Reproduce

1. Create the flow with the following yaml:
```
id: compression-1
namespace: company.team
tasks:
  - id: httpdownload
    type: io.kestra.plugin.fs.http.Download
    uri: "https://raw.githubusercontent.com/kestra-io/datasets/main/csv/products.csv"
  - id: "file_compress"
    type: "io.kestra.plugin.compress.FileCompress"
    from: "{{ outputs.httpdownload.uri }}"
    compression: Z
```
2. Execute this flow.

### Environment Information

- Kestra Version: 0.14.4
- Plugin version: 0.14.4
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker): N/A

### Example flow

```
id: compression-1
namespace: company.team
tasks:
  - id: httpdownload
    type: io.kestra.plugin.fs.http.Download
    uri: "https://raw.githubusercontent.com/kestra-io/datasets/main/csv/products.csv"
  - id: "file_compress"
    type: "io.kestra.plugin.compress.FileCompress"
    from: "{{ outputs.httpdownload.uri }}"
    compression: Z
```
