### ISSUE TITLE
Password Encryption Feature

### ISSUE THREAD

**Issue by ViktorTrojan** [kestra-io/plugin-compress#89]
### Feature description

I'd love to see a password encryption/decryption feature in this plugin. The `openssl enc -aes-256-cbc -pbkdf2 -iter <count>` method is the one I prefer to use on linux and offers strong security.

Adding this would greatly enhance your plugin's functionality and appeal to users who prioritize data security.

**Comment by Pradumnasaraf** [comment]
### QA Done ✅

1) ARGON2ID encrypt → decrypt round-trip (decrypt auto-detects format).

```yaml
id: qa_argon2id
namespace: qa.plugin-compress

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://sample-files.com/downloads/compressed/zip/basic-text.zip

  - id: encrypt
    type: io.kestra.plugin.compress.FileEncrypt
    from: "{{ outputs.download.uri }}"
    password: "test-password"
    keyDerivation: ARGON2ID
    argon2TimeCost: 1
    memory: 8192
    parallelism: 1

  - id: decrypt
    type: io.kestra.plugin.compress.FileDecrypt
    from: "{{ outputs.encrypt.uri }}"
    password: "test-password"

  - id: decompress
    type: io.kestra.plugin.compress.ArchiveDecompress
    from: "{{ outputs.decrypt.uri }}"
    algorithm: ZIP

  - id: assert_round_trip
    type: io.kestra.plugin.core.execution.Fail
    condition: "{{ outputs.decompress.files | length != 6 }}"
```

<img width="2560" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2745b12b-6140-4a4a-9aad-339614782f6f" />


2) Encrypt with one password, try to decrypt with another. Failed as expected due to the incorrect password 

```yaml
id: qa_wrong_password
namespace: qa.plugin-compress

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://sample-files.com/downloads/compressed/zip/basic-text.zip

  - id: encrypt
    type: io.kestra.plugin.compress.FileEncrypt
    from: "{{ outputs.download.uri }}"
    password: "correct-password"
    iterations: 100000

  - id: decrypt_with_wrong_pwd
    type: io.kestra.plugin.compress.FileDecrypt
    from: "{{ outputs.encrypt.uri }}"
    password: "WRONG-password"
    iterations: 100000
```


<img width="2560" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7f9a4306-4e37-407f-ad88-479e71de7719" />
